### ISSUE TITLE
mips64le

### ISSUE THREAD

**Issue by tianon** [docker-library/gcc#67]
This image fails to build on `mips64le` (all of `gcc:10.1.0`, `gcc:9.3.0`, *and* `gcc:8.4.0`):

```
In file included from /usr/src/gcc/libgcc/../gcc/tsystem.h:87,
                 from /usr/src/gcc/libgcc/libgcc2.c:27:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:494: _muldi3.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/src/gcc/libgcc/../gcc/tsystem.h:87,
                 from /usr/src/gcc/libgcc/libgcc2.c:27:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:494: _negdi2.o] Error 1
In file included from /usr/src/gcc/libgcc/../gcc/tsystem.h:87,
                 from /usr/src/gcc/libgcc/libgcc2.c:27:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:494: _lshrdi3.o] Error 1
In file included from /usr/src/gcc/libgcc/../gcc/tsystem.h:87,
                 from /usr/src/gcc/libgcc/libgcc2.c:27:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:494: _ashldi3.o] Error 1
make[3]: Leaving directory '/tmp/tmp.QVGBjgKB6B/mips64el-linux-gnuabi64/libgcc'
make[2]: *** [Makefile:21918: all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/tmp/tmp.QVGBjgKB6B'
make[1]: *** [Makefile:27156: stage1-bubble] Error 2
make[1]: Leaving directory '/tmp/tmp.QVGBjgKB6B'
make: *** [Makefile:950: all] Error 2
```

(All three versions give a backtrace similar to this one, all complaining about `bits/libc-header-start.h`)

**Comment by tianon** [comment]
Three and a half years later, I think I'm OK with just not supporting `mips64le` here. :smile:

Happy to reconsider if there's sufficient proof that the upstream issues are fixed and the builds will likely succeed. :bow:
